endpoints:
  - path: /api/comments
    method: GET
    requestConfig:
      url: https://jsonplaceholder.typicode.com/comments?postId={{postId}}
      method: GET
  - path: /api/posts/comments
    method: GET
    requestConfig:
      url: https://jsonplaceholder.typicode.com/posts/{{postId}}/comments
      method: GET
  - path: /api/auth/login
    method: GET
    requestConfig:
      url: https://jsonplaceholder.typicode.com/posts # [TODO] fix later
      isRedirect: true
  - path: /api/auth/callback
    method: GET
    requestConfig:
      url: https://jsonplaceholder.typicode.com/posts # [TODO] fix later
      method: POST
      headers:
        Content-Type: application/x-www-form-urlencoded
      body:
        client_id: ${CLIENT_ID}
        client_secret: ${CLIENT_SECRET}
        grant_type: authorization_code
        code: '{{code}}'
        redirect_uri: https://jsonplaceholder.typicode.com/posts
