endpoints:
  - path: /api/comments
    method: GET
    requestConfig:
      url: https://jsonplaceholder.typicode.com/comments?postId={{postId}}
      method: GET
  - path: /api/posts/comments
    method: GET
    requestConfig:
      url: https://jsonplaceholder.typicode.com/posts/{{postId}}/comments
      method: GET
