endpoints:
  - path: /api/comments
    method: GET
    requestConfig:
      url: https://jsonplaceholder.typicode.com/comments?postId={{postId}}
      method: GET
  - path: /api/posts/comments
    method: GET
    requestConfig:
      url: https://jsonplaceholder.typicode.com/posts/{{postId}}/comments
      method: GET
  - path: /api/auth/login
    method: GET
    requestConfig:
      url: http://keycloak/auth/realms/${KEYCLOAK_REALM_NAME}/protocol/openid-connect/auth?response_type=code&client_id=${KEYCLOAK_CLIENT_ID}&redirect_uri=http%3A%2F%2Fnestjs-bff%2Fapi%2Fauth%2Fcallback&scope=${KEYCLOAK_SCOPE}
      isRedirect: true
  - path: /api/auth/callback
    method: GET
    requestConfig:
      url: http://keycloak/auth/realms/${KEYCLOAK_REALM_NAME}/protocol/openid-connect/token
      method: POST
      headers:
        Content-Type: application/x-www-form-urlencoded
      body:
        client_id: ${KEYCLOAK_CLIENT_ID}
        client_secret: ${KEYCLOAK_CLIENT_SECRET}
        grant_type: authorization_code
        code: '{{code}}'
        redirect_uri: http://nestjs-bff/api/posts
